In [14]:
# addition of two matrices using array

def add_matrices(mat1, mat2):
    # mat1 and mat2 must both be of same order
    mat3 = []
    for row in range(len(mat1)):
        mat3.append([])
        
        for col in range(len(mat1[row])):
            mat3[-1].append(mat1[row][col] + mat2[row][col])

    return mat3

mat1 = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

mat2 = [
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
]

print(add_matrices(mat1, mat2))

[[12, 14, 16], [18, 20, 22], [24, 26, 28]]


In [13]:
#### addition of two matrices using numpy
import numpy as np
mat1 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

mat2 = np.array([
    [11, 12, 13],
    [14, 15, 16],
    [17, 18, 19]
])

print(mat1 + mat2)

[[12 14 16]
 [18 20 22]
 [24 26 28]]
